### ISSUE TITLE
Add Time.from(DateTime)

### ISSUE THREAD

**Issue by bsutton** [AndrewPiterov/date_time#5]
create a Time instance from a DateTime.

**Comment by AndrewPiterov** [comment]
You already can extract `Time` from `DateTime` 

```dart
final time = DateTime.now().time;
print(time); // 12:03:15
```

**Comment by bsutton** [comment]
I didn't realize that and perhaps that's the point.

When building libraries I like to make things symmetrical as it makes it easy to find things.
As such I think it would still be worth including.

**Comment by AndrewPiterov** [comment]
could you provide the desired interface?

**Comment by bsutton** [comment]
It should mirror the the Date.from method.

 Time.from(DateTime.now());

Whilst we are here.
I wonder if its worth having copyWith methods so you can selectively just adjust one or two values

Time.from(DateTime.now()).copyWith(second: 0);

as opposed to

final t = Time.from(DateTime.now())
final t1 = Time(hour: t.hour, minute: t.minute, second: 0);

**Comment by AndrewPiterov** [comment]
[0.6.0](https://github.com/AndrewPiterov/date_time/releases/tag/0.6.0)
