### ISSUE TITLE
consider change named args to match Duration and arg conventions.

### ISSUE THREAD

**Issue by bsutton** [AndrewPiterov/date_time#6]
Not a big issue but the named arguments on Time are inconsistent with Duration.

The Dart Duration class fully spells out each argument rather than using abbreviations.
In my opinion using a pattern consistent with Dart would make the library easier to use.

I also note some odd inconsistency between the Date and the Time ctors:

  const Date(
    this.year,
    this.month,
    this.day,
  );

 const Time(
    this.hours, {
    this.mins = 0,
    this.secs = 0,
  })

I guess the argument was that defaults for min and seconds made some sense.

I would argue that all of the args should be named parameters.

I don't like method signatures that have multiple arguments with the same type. It's way too easy to pass them in the wrong order.  Using named arguments makes these type of mistakes obvious.

**Comment by AndrewPiterov** [comment]
I agree with you 
_I don't like method signatures that have multiple arguments with the same type. It's way too easy to pass them in the wrong order. Using named arguments makes these type of mistakes obvious._

But I'd like to make `Date Time` and `Date` interchangeable almost following `DateTime`'s positional optional parameters, and `Date` more transparent with required `month` and `day`:
```dart
final dateTime = DateTime(2000);
final date = Date(2020, 1, 1);
```

**Comment by bsutton** [comment]
I hadn't really absorbed the fact that they were using optional parameters for DateTime.

I'm now torn.

I like the idea of being consistent with Dart but I think they probably made a poor choice here.
I can't say that I've ever initialised a date object to just a year in all my years of programming so the interface looks fairly useless.
The named arguments makes things clearer (particularly when you consider m/d/y, d/m/y... variants). 

Personally I would still prefer to see them all as named args.

What about
```dart
Date({required int year, int month = 1, int day = 1});

Date(year: 2000);

and
Time({required int hour, int minute=0, int second=0});

Time(hour: 12);
```

This provides similar feel but IMO a superior interface.

One final note. The DateTime class uses 'hour' not 'hours', 'minute' not 'minutes'...

**Comment by AndrewPiterov** [comment]
Agree, looks more clear, seems the next release will be with breaking changes

**Comment by AndrewPiterov** [comment]
[0.6.0](https://github.com/AndrewPiterov/date_time/releases/tag/0.6.0)
