### ISSUE TITLE
Date.now and Time.now should be factories

### ISSUE THREAD

**Issue by bsutton** [AndrewPiterov/date_time#8]
The current Date.now method is a getter.

The DateTime.now is a constructor.

```
  static Date get now => DateTime.now().date;
```
changes this to a factory for consistency

```
 Date.now() => DateTime.now().date;
Time.now() => DateTime.now().time;
```

**Comment by AndrewPiterov** [comment]
[0.6.0](https://github.com/AndrewPiterov/date_time/releases/tag/0.6.0)
